#!/usr/bin/env bash
#script that transfers a file from our client to a server
#$0: the bash script
#$1: PATH_TO_FILE
#$2: IP of the server
#$3: USERNAME
#$4: PATH_TO_SSH_KEY

if [ $# -lt 3 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
  exit 1
fi
scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/$1
