#!/usr/bin/env bash

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Allow Nginx through the firewall
sudo ufw allow 'Nginx HTTP'

# Create the index.html file with "Hello World!"
echo "Hello World!" | sudo tee /var/www/html/index.html

# Configure Nginx
sudo tee /etc/nginx/sites-available/default > /dev/null <<EOF
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;

    location / {
        try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
        rewrite ^ https://github.com/Therese-Claire permanent;
    }
}
EOF

# Start or reload Nginx
if [ -z "$(pgrep nginx)" ]; then
    sudo service nginx start
else
    sudo service nginx reload
fi
