#!/usr/bin/env bash
# installs and configures a load balancer on a server

sudo apt-get -y update
sudo apt-get -y install haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend my_frontend
	bind *:80
	mode http
	stats enable
        stats uri /haproxy?stats
        option forwardfor
	default_backend hbnb_backend

backend my_backend
	mode http
	balance roundrobin
	server 522745-web-01 52.4.1.57:80 check
	server 522745-web-02 52.3.244.12:80 check
	timeout client 30s
	timeout connect 30s
	timeout server 30s
EOF

if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy reload
fi
