#!/usr/bin/env bash
# This script installs and configures a load balancer on a server

set -e

sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.*


echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

# Configure HAProxy
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOF
frontend my_frontend
    bind *:80
    mode http
    stats enable
    stats uri /haproxy?stats
    option forwardfor
    default_backend my_backend
    timeout client 30s
    timeout connect 30s
    timeout server 30s

backend my_backend
    mode http
    balance roundrobin
    option http-server-close
    server 526174-web-01 54.236.26.138:80 check
    server 526174-web-02 3.84.158.55:80 check
    timeout client 30s
    timeout connect 30s
    timeout server 30s
EOF


if [ "$(pgrep -c haproxy)" -le 0 ]; then
	sudo service haproxy start
else
	sudo service haproxy reload
fi
