#!/usr/bin/env bash
# script that configures a server to listen on port 80

sudo apt update
sudo apt install net-tools utw -y

#checks for conflicting services
sudo netstat -tuln | grep 80

sudo ufw allow 'Nginx HTTP'

sudo sed -i 's/#listen 80;/listen 80;/g' /etc/nginx/sites-available/default

sudo systemctl restart nginx
