#!/usr/bin/env bash
#This script displays To infinity and beyond indefinitely,
#and sleep 2 is added in between each iteration.

counter=1

while true; do
	echo "To infinity and beyong"
	sleep 2
	
	(( counter++ ))
done
