#!/usr/bin/env bash
#This script displays To infinity and beyond indefinitely,
#and sleep 2 is added in between each iteration.

trap 'echo "I am invincible!!!"; exit 0' SIGTERM

while true; do
	echo "To infinity and beyond"
	sleep 2
done
