#!/usr/bin/env bash
#This script displays Best School 10 times, but for the 9th iteration,
#displays Best School and then Hi on a new line.

counter=1

while [ $counter -lt 10 ];
do
echo "Best School"
((counter++))
if [ $counter -eq 9 ];
then
echo "Hi"
fi
done
