#!/usr/bin/env bash
#Fix issue so that when i curl 0:8080 which is mapped to my docker 
#container it returns Hello Holberton


echo 'Hello Holberton' > /var/www/html/index.html
service apache2 start
